### ISSUE TITLE
URL is marked as dangerous by Google but it's not in WebRisk API?

### ISSUE THREAD

**Issue by CDNievas** [googleapis/python-webrisk#152]
Hi I have these URLs listed below that are marked as dangerous by Google (can check by visit or using this tool of google [https://transparencyreport.google.com/safe-browsing/search](https://transparencyreport.google.com/safe-browsing/search)) but not are in the WebRisk API

- http://20.106.75.26/index.php
- https://mercadolivre-produtos.com/mercadolivre/produto/29373737373/choice_frete_plan.php

I'm checking if the web is listed as dangerous in WebRisk with this code

```python

import app
from app.services.secrets import get_gcp_credentials

from google.oauth2 import service_account
from google.cloud.webrisk_v1.services.web_risk_service import WebRiskServiceClient
from google.cloud.webrisk_v1.types.webrisk import ThreatType

class _GCP:

    def init(self):
        file = get_gcp_credentials()

        credentials = service_account.Credentials.from_service_account_file(file.name)

        # Configure clients
        self.risk = WebRiskServiceClient(credentials=credentials)

        file.close()
        return self


_GCP_Client = _GCP().init()

def check_url(url):
    resp = _GCP_Client.risk.search_uris(uri=url, timeout=5, threat_types=[ThreatType.SOCIAL_ENGINEERING, ThreatType.MALWARE, ThreatType.UNWANTED_SOFTWARE])
    return resp != None
```

This code is working because I have another URL that if I check, its result that the URL is marked in both places as dangerous

http://belarminoleiloes20-wixsite-com.filesusr.com/html/ba60bf_fc69ef04f9b325f0a0ebcce95d2febfd.html

I'll wait for your response. Thanks!

**Comment by busunkim96** [comment]
Hi @CDNievas,

I've directed this question to the WebRisk API team and will let you know when I get a response.

**Comment by CDNievas** [comment]
Hi, any news about this?

**Comment by CDNievas** [comment]
@busunkim96 ?

**Comment by CDNievas** [comment]
Hi, any news about this? Because we received an email saying that in 60 days this api will become paid and we need that it's works correctly before paying anything...

**Comment by busunkim96** [comment]
Hi @CDNievas,

Apologies for the delayed response! I received this response from the for your original question:

> Security systems at Google may have different rules and reactions to observed threats.  Slight difference should be expected.

If you notice any differences like this in the future, please do open another issue and we will be happy to investigate.

Thank you!
